version: '3.8'

services:
  db:
    container_name: hello-db
    image: mysql:8.0
    ports:
      - 3305:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hello
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234567890
      TZ: 'Asia/Seoul'
    networks:
      - hello_network
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 2s
      retries: 100


  app:
    container_name: hello-backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hello_network

networks:
  hello_network:

volumes:
  mysql-data:

